version: '3.8'

services:
  postgres:
    image: postgres:14
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d finpulse" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: finpulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - finpulse-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  liquibase-migrations:
    image: liquibase/liquibase:latest
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finpulse-network
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/finpulse
      - --username=postgres
      - --password=password
      - --classpath=/liquibase/classpath/postgresql-42.7.3.jar
      - update
    volumes:
      - ./migrations/changelog:/liquibase/changelog
      - ./liquibase-drivers:/liquibase/classpath
    restart: "no"

#  redis:
#    image: redis:7-alpine
#    ports:
#      - "6379:6379"
#    networks:
#      - finpulse-network
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    networks:
#      - finpulse-network
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    hostname: kafka
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    ports:
#      - "9092:9092"
#    networks:
#      - finpulse-network
#
#  minio:
#    image: minio/minio:latest
#    container_name: minio
#    environment:
#      - MINIO_ROOT_USER=minioadmin
#      - MINIO_ROOT_PASSWORD=minioadmin
#    command: server /data --console-address ":9001"
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - minio_data:/data
#    networks:
#      - finpulse-network
#
#  # Бэкенд сервисы
#  apigateway:
#    image: finpulse/apigateway:latest
#    depends_on:
#      liquibase-migrations:
#        condition: service_completed_successfully
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - DB_URL=jdbc:postgresql://postgres:5432/finpulse
#      - REDIS_HOST=redis
#      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#    networks:
#      - finpulse-network
#    ports:
#      - "8080:8080"
#
#  aggregationservice:
#    image: finpulse/aggregationservice:latest
#    depends_on:
#      liquibase-migrations:
#        condition: service_completed_successfully
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - DB_URL=jdbc:postgresql://postgres:5432/finpulse
#      - REDIS_HOST=redis
#      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#      - BANK_CLIENT_ID=team200
#      - BANK_CLIENT_SECRET=5OAaa4DYzYKfnOU6zbR34ic5qMm7VSMB
#    networks:
#      - finpulse-network
#    ports:
#      - "8082:8082"

volumes:
  postgres_data:
  minio_data:

networks:
  finpulse-network:
    driver: bridge