version: '3.8'

services:
  # База данных
  postgres:
    image: postgres:14
    container_name: finpulse-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d finpulse" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: finpulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finpulse-network
    restart: "no"

  #Миграции
  liquibase-migrations:
    image: liquibase/liquibase:latest
    container_name: finpulse-liquibase
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finpulse-network
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/finpulse
      - --username=postgres
      - --password=password
      - --classpath=/liquibase/classpath/postgresql-42.7.3.jar
      - update
    volumes:
      - ./migrations/changelog:/liquibase/changelog
      - ./liquibase-drivers:/liquibase/classpath
    restart: "no"

  # Кэш
  redis:
    image: redis:7-alpine
    container_name: finpulse-redis
    ports:
      - "6379:6379"
    networks:
      - finpulse-network
    restart: unless-stopped

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: ZVYcJ0GdQO2V7cLDgOkPAg==
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 168
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - finpulse-network
    restart: unless-stopped

  # Object Storage
  minio:
    image: minio/minio:latest
    container_name: finpulse-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    networks:
      - finpulse-network
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  #Frontend
  frontend:
    image: lohop/finpulse-frontend:latest
    container_name: finpulse-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://apigateway:8080
      - REACT_APP_NOTIFICATIONS_WS_URL=ws://apigateway:8080/ws/notifications
      - REACT_APP_FORECASTS_WS_URL=ws://apigateway:8080/ws/forecasts
    networks:
      - finpulse-network
    restart: unless-stopped


  #Api Gateway
  apigateway:
    image: lohop/apigateway:latest
    container_name: finpulse-apigateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=EY4ZdvgJ4wnFjpeKYA2qmnCztsMR4wMAICMw7wrnSIaTRYCm51BWOaPmNtrn3n90
      - REDIS_HOST=redis
      - USER_SERVICE_URL=http://userservice:8081
      - NOTIFICATION_SERVICE_URL=http://notificationservice:8084
      - AGGREGATION_SERVICE_URL=http://aggregationservice:8082
    ports:
      - "8080:8080"  # оставляем для отладки
    depends_on:
      - redis
      - userservice
      - notificationservice
      - aggregationservice
    networks:
      - finpulse-network
    restart: unless-stopped

  # Микросервисы
  userservice:
    image: lohop/finpulse-userservice:latest
    container_name: finpulse-userservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres:5432/finpulse
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=EY4ZdvgJ4wnFjpeKYA2qmnCztsMR4wMAICMw7wrnSIaTRYCm51BWOaPmNtrn3n90
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - finpulse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  aggregationservice:
    image: lohop/finpulse-aggregationservice:latest
    container_name: finpulse-aggregationservice
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres:5432/finpulse
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - BANK_CLIENT_ID=team214
      - BANK_CLIENT_SECRET=5XuUMVksUK2mvLYD
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - finpulse-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  notificationservice:
    image: lohop/finpulse-notificationservice:latest
    container_name: finpulse-notificationservice
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://postgres:5432/finpulse
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL:-http://localhost:9000/ml-charts}
    depends_on:
      - postgres
      - redis
      - kafka
      - minio
    networks:
      - finpulse-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  ml-forecast-service:
    image: lohop/finpulse-mlservice:latest
    container_name: finpulse-mlservice
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=finpulse
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_SECURE=0
    depends_on:
      - kafka
      - postgres
      - minio
    networks:
      - finpulse-network
    restart: unless-stopped

  recommendation-service:
    image: lohop/finpulse-recommendationservice:latest
    container_name: finpulse-recommendation-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=finpulse
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PRODUCT_SERVICE_URL=http://product-service:8085
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - postgres
      - redis
    networks:
      - finpulse-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  kafka_data:
    driver: local
  minio_data:
    driver: local

networks:
  finpulse-network:
    driver: bridge
